### ISSUE TITLE
[Recommendation - Book Hosting / Diagrams]

### ISSUE THREAD

**Issue by m0ham3dx** [jtriley-eth/the-ethereum-virtual-machine#2]
# Recommendation - Hosting (Free)

I have hosted my own mdbook's on two platforms so far. My criteria were 
- Fast setup 
- Minimum Tinkering 
- CI through repo directly without Github Actions 

I found the following two which fits my criteria. I am not mentioning [netlify](https://www.netlify.com/), because that can be a failsafe, since obviously they are leaders for any kind of single sites with support for multiple platforms.

1. [Fleek](https://fleek.co/) - This is like netlify but on [IPFS](https://ipfs.io/) - The big problem with web3 hosting on IPFS is its slow to the point you will leave before the page loads. Fleek has tight integration with decentralized DNS (HNS , ENS). Hosting on this is free with some limitations, but the free tier is good enough even for a 100 page mdbook. 

2. [Cloudflare Pages](https://pages.cloudflare.com/) - [Foundry Official Manual](https://book.getfoundry.sh/) is hosted on Cloudflare Pages. Fits my criteria. Free tier is good enough even for very large books. 

# Recommendation - Diagrams

As you most probably aware MDBOOK also has support for both 
1. [mermaid](https://mermaid-js.github.io/mermaid/#/) via [mdbook-mermaid](https://lib.rs/crates/mdbook-mermaid) & 
2. [plantuml](https://plantuml.com/) via [mdbook-mermaid](https://lib.rs/crates/mdbook-plantuml). 
But github supports mermaid natively (for diagrams). You could consider using it. Simple setup process for both authors and contributors.

**Comment by jtriley2p** [comment]
I don't have a hosting preference, but Couldflare Pages seems like a good choice. However, I'm looking to complete some of the current `TODO`'s in the repo before publishing, so we have time to decide.

---

As for the diagrams, I like mermaid in Github, but I've never used it with mdbook. Feel free to submit a PR with it added and any additional instructions (if any). Otherwise, I can look into this soon to add it in!
